name: CI/CD Pipeline - frontend Node.js

on:
  push:
    branches:
      - master # ou master, dependendo do padrão do seu repositório

jobs:
  # 1. Análise de Qualidade com SonarQube
  sonarcloud:
    name: SonarQube Analysis
    runs-on: self-hosted
    steps:
      - name: Checkout do código
        # Pinado na versão v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=DiogoMarassi_frontend
            -Dsonar.organization=diogomarassi
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**
  # 2. Deploy na AWS EC2 (Só roda se o Sonar passar)
  deploy:
    name: Deploy to EC2
    needs: sonarcloud
    runs-on: self-hosted
    steps:
      - name: Deploy na EC2 sem ssh (via runner)
        # Pinado na versão v1.0.3 em vez de @master
        run: |
            # 1. Entra na pasta do seu projeto (Lembre-se de ajustar o nome abaixo!)
            cd /home/ubuntu/lingua/frontend
            
            # 2. Puxa as novidades do GitHub
            git pull origin master
            
            # 3. Instala pacotes novos e sincroniza o banco
            npm install
            
            # 4. Refaz o build do NestJS com o código novo
            npm run build
            
            # 5. Reinicia a API no PM2
            pm2 restart frontend-web || pm2 start npm --name "frontend-web" -- start

            pm2 save
